### ISSUE TITLE
make it play nice with SwiftyJSON

### ISSUE THREAD

**Issue by johndpope** [ovenbits/ModelRocket#1]
https://github.com/SwiftyJSON/SwiftyJSON

**Comment by aranasaurus** [comment]
I don't understand, how would this "play nicely" with that? They seem to be two libraries that solve the same problem in fairly different ways.

**Comment by johndpope** [comment]
I see - I'll close this enhancement suggestion - but consider adding more information around integration with afnetworking / parsing json examples.
