### ISSUE TITLE
JSONTransformableDateFormatter doesn't transform dates properly

### ISSUE THREAD

**Issue by tomparkp** [ovenbits/ModelRocket#10]
The current NSDateFormatter for transforming ISO8601 appears to have some issues with regards to the date format:

`dateFormatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"`

First putting the `'Z'` in single quotes seems to escape it so that it always assumes the date string is in GMT therefore ignoring timezone offset included in the string.

For example if I use ModelRocket to parse the following date string from my JSON:
`"2015-10-04T01:00:00.000Z"`

I actually end up with:
`"2015-10-04T05:00:00.000Z"`

This is because by default NSDateFormatter uses the local timezone of the device (in my case EST) so when this combines with the escaped Z the time is off by 4 hours.

This can be corrected by eliminating the single quotes around the Z so it accepts the offsets properly.

Additionally having the `SSS` means that the example string `2015-05-31T19:00:17+00:00` from the documentation will fail to parse because its missing milliseconds.

The last thing is that its recommended to add the following just in case the device is not using the gregorian calendar:

`formatter.locale = NSLocale(localeIdentifier: "en_US_POSIX")`

https://github.com/ovenbits/ModelRocket/blob/866b1a714ffd86f40b290a4e032be87376529c05/ModelRocket/JSONTransformable.swift#L83

**Comment by jlandon** [comment]
@tompark-IO thanks for the tip! This is fixed in **1.2.2**. Cheers!
