### ISSUE TITLE
Internal property description clash when overriding

### ISSUE THREAD

**Issue by argentounce** [ovenbits/ModelRocket#13]
Hello all! Nice library :)

Can't use `let description = PropertyArray<String>(key: "description")`

``` json
    "description": [
        "4 claras de huevo revueltas con ½ taza de espinaca y ½ taza de champiñones",
        "1 tortilla de maíz",
        "½ toronja"
      ]
```

I know, is a collection of ingredients and it should be named different. Anyhow, in the case that something really need the name description, like in a blogpost ?

Saludos

**Comment by jlandon** [comment]
Hey @argentounce,

`description` is a reserved property name for the `NSObjectProtocol` and `CustomStringConvertible` protocols, so you won't be able to use that for your model. However, the property name and JSON key can be different, so something like this would work instead:

``` swift
let listOfDescriptions = PropertyArray<String>(key: "description")
```

The model's property can be named something other than "description", but you can continue to use "description" as the JSON key without any problems. Hope that helps! :)

**Comment by argentounce** [comment]
Hello @jlandon !

Thanks. I didn't know that `description` is a reserved word. I did something similar of your proposal. It is a great library and I would continue using it. Is there any plans of making a showcase, you know, "Apps that are using this?" Im combining this with [FutureKit](https://github.com/FutureKit/FutureKit) and is a bliss :smile:

**Comment by jlandon** [comment]
@argentounce I haven't thought about doing that right now, but it's always great to hear that others find the library useful :)
