### ISSUE TITLE
Typed array models don't work as documented

### ISSUE THREAD

**Issue by thatjuan** [ovenbits/ModelRocket#18]
According to the examples in the readme, this is how you create a typed array model: 

```
class Vehicle: Model {
    let make  = Property<String>(key: "make")
    let model = Property<String>(key: "model", required: true)
    let year  = Property<Int>(key: "year") { year in
        if year < 2015 {
            // offer discount
        }
    }
    let color = Property<UIColor>(key: "color", defaultValue: UIColor.blackColor())
}

class Vehicles: Model {
    let vehicles = PropertyArray<Vehicle>(key: "vehicles")
}

```

However, this results in error "Type 'Vehicle' does not conform to protocol 'JSONTransformable'

Adding the "JSONTransformable" protocol to Vehicle fixes the issue.

**Comment by jlandon** [comment]
Thanks @thatjuan! `Model` subclasses get the `fromJSON` and `toJSON` implementations on `JSONTransformable` for free, but the model _does_ still need to specify itself as `JSONTransformable`. I'll update the README to fix that. :+1:
