### ISSUE TITLE
Enums?

### ISSUE THREAD

**Issue by tomparkp** [ovenbits/ModelRocket#3]
Does Modelrocket support enums or is there a recommended practice for implementing enum properties in Modelrocket models?

Thanks,
Tom

**Comment by jlandon** [comment]
Hey Tom,

Thanks for the question! ModelRocket _does_ support enum properties, as long as the enum conforms to the `JSONTransformable` protocol.

Using the `Vehicle` model from the README, here's an example of how you could use an enum to parse the material of a vehicle's interior:

``` swift
enum VehicleInterior: String {
    case Fabric = "fabric"
    case Leather = "leather"
}

extension VehicleInterior: JSONTransformable {
    static func fromJSON(json: JSON) -> VehicleInterior? {
        return VehicleInterior(rawValue: json.stringValue)
    }
    func toJSON() -> AnyObject {
        return rawValue
    }
}

class Vehicle: ModelRocket {
   let interior = Property<VehicleInterior>(key: "interior")
}
```
