### ISSUE TITLE
Include ModelRocket source directly?

### ISSUE THREAD

**Issue by ghost** [ovenbits/ModelRocket#4]
I'd like to directly include the ModelRocket sources in my project.  No pod, no cartfile.
Do you foresee any issues?

Thanks,
--dan

**Comment by jlandon** [comment]
Hey Dan,

You can definitely include the source directly in your project without issue, but unless you're targeting iOS 7, using a dependency manager and dynamic frameworks is a good idea. :)

And if you _are_ targeting iOS 7, you might consider using git submodules to manage the dependency
